### PR TITLE
Add theme-config to new repository

### PR DESCRIPTION
**Pull request by justinmayer**
This adds the `theme-config` plugin to a new repository under the Pelican Plugins organization.

### CODE REVIEW

**Comment by justinmayer** [comment]
@galaxy4public: I'm going to add a few other minor changes to this PR. Please have a look and let me know what you think.

**Comment by galaxy4public** [comment]
I appreciate your time, @justinmayer , thank you!

**Comment by justinmayer** [comment]
My pleasure. Once again, my sincere apologies for the long delay.

One additional note for future releases… Publishing GitHub releases and PyPI packages is fully automated in the existing GitHub Actions workflow, using a tool I helped build called [AutoPub](https://justinmayer.com/projects/autopub/). The flow is mentioned in the [development docs](https://docs.getpelican.com/en/latest/contribute.html#using-git-and-github), and by way of example, you can see the [commit that was just pushed](https://github.com/pelican-plugins/feed-filter/commit/c828d066467e60dddf580407e4a2679004e6961a) a few minutes ago to publish the [Feed Filter 1.1.0 release](https://github.com/pelican-plugins/feed-filter/releases/tag/1.1.0).

**Comment by justinmayer** [comment]
I see just now that you used the above-mentioned AutoPub flow, but it seems perhaps after you had already published it manually, resulting in a spurious 2.0.0 version being published right afterward? In an AutoPub context, the idea is to **never** manually change the version number in the `pyproject.toml` file, as that is automatically incremented based on the `patch | minor | major` designation inside the `RELEASE.md` file.

**Comment by galaxy4public** [comment]
@justinmayer, yeah -- I had a tough day: was in a shooting competition for 8 hours, so my brain is not working at 100%, hence I had to figure out everything the hard way (despite that you were prompt enough to warn me here, I did not get the notification until I already made a mistake).  Anyway, everything is settled now, I think.  I also opened an issue in AutoPub re: the documentation (just an observation from a newcomer, so may be valuable).  Finally, I submitted a PR re: to the needed change to the workflow since GitHub is going to remove the set-output command in May this year.

**Pull request merged**
